
import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from 'react';
import ReduxProvider from './providers/ReduxProvider';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { Toaster } from 'react-hot-toast';




export const metadata: Metadata = {
  title: "WhatBytes - Your Online Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
         <ReduxProvider>
          <Toaster position="top-center" reverseOrder={false} />
          <Header />
          <main className="min-h-[80vh]">{children}</main>
          <Footer />
      </ReduxProvider>
      </body>
    </html>
  );
}